

# policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb/Feb11_21-19-24_debug_new_phase_obs_omni_direction/exported/policy_lstm_None.pt"
# policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb/Feb12_10-37-02_debug_ang_vel/exported/policy_lstm_50000.pt"
# OK
policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb/Feb13_15-53-50_big_mass_ankle_penalty_stance_base_vel_feet_contact_force/exported/policy_lstm_None.pt"
# action delay
policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb/Feb15_17-29-01_big_mass_ankle_penalty_stance_base_vel_feet_contact_force_action_delay/exported/policy_lstm_None.pt"

policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum/Feb18_14-53-55_range_leading/exported/policy_lstm_-1.pt"

policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum/Feb21_13-40-26_range_leading_cmd0_gait_no_est/exported/policy_lstm_-1.pt"

policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum_MLP_est/Feb27_17-21-37_range_leading_RAMC_new_MLP_est_multi_terrains_64_32_no_rewards_all_est_all_motion_motion_leading/exported/policy_lstm_-1.pt"

policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb/Feb25_16-25-55_big_mass_ankle_penalty_stance_base_vel_feet_contact_force_action_delay_add_trimesh/exported/policy_lstm_None.pt"

# for whole body policy control
################################################
upper_policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_upper/Mar03_11-48-45_range_leading_terrain_server_load_new_cmd_new_cul_quick_no_torque_smooth_right_reward_relative_025_true_scale_new_cmd_cul/exported/policy_lstm_-1.pt"

lower_policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb/Feb25_16-25-55_big_mass_ankle_penalty_stance_base_vel_feet_contact_force_action_delay_add_trimesh/exported/policy_lstm_None.pt"


upper_policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_upper/Mar04_10-33-14_true_urdf_csv_no_est/exported/policy_lstm_-1.pt"

lower_policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum/Mar03_23-39-20_range_leading_terrain_load_terrain_cul_true_urdf_true_csv_continue1/exported/policy_lstm_-1.pt"

############################################


# est
# policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum_MLP_est_MLP_ac/Feb28_15-17-59_range_leading_all_MLP_terrain/exported/policy_est_-1.pt"
# 3.4
# policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum/Mar03_23-39-20_range_leading_terrain_load_terrain_cul_true_urdf_true_csv_continue1/exported/policy_lstm_-1.pt"

# 3.4 new urdf est
# policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum_MLP_est_MLP_ac/Mar03_23-22-21_range_leading_all_MLP_terrain_true_urdf_true_csv_2/exported/policy_est_-1.pt"


#########################3
# 3.7
policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum/Mar06_21-50-49_range_leading_terrain_load_terrain_cul_true_urdf_true_csv_continue3/exported/policy_lstm_8000.pt"

# policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum/Mar03_23-39-20_range_leading_terrain_load_terrain_cul_true_urdf_true_csv_continue1/exported/policy_lstm_-1.pt"

# policy_path : "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb/Mar06_22-12-13_big_mass_ankle_penalty_stance_base_vel_feet_contact_force_action_delay_add_trimesh_new_urdf/exported/policy_lstm_10000.pt"

# policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum/Feb18_14-53-55_range_leading/exported/policy_lstm_-1.pt"

policy_path: "/home/bcj/new_unitree_rl_gym/logs/h1_2_wb_curriculum/lower3_Mar10_01-45-12_lower_3/exported/policy_lstm_12800.pt"


xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/h1_2/meshes/scene_21dof.xml"


# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [
  200, 200, 200, 300, 40, 40, 
  200, 200, 200, 300, 40, 40,
  300,
  120, 120, 120, 80,
  120, 120, 120, 80
]
kds: [
  2.5, 2.5, 2.5, 4, 2, 2,
  2.5, 2.5, 2.5, 4, 2, 2,
  3,
  2, 2, 2, 1,
  2, 2, 2, 1
]

default_angles: [0, -0.4, 0.0, 0.8, -0.4, 0.0, 
                 0, -0.4, 0.0, 0.8, -0.4, 0.0,
                 0.0,
                 0.4, 0.2, 0, 0.3,
                 0.4, -0.2, 0, 0.3]

# default_angles: [0, -0.16, 0.0, 0.36, -0.2, 0.0, 
#                  0, -0.16, 0.0, 0.36, -0.2, 0.0,
#                  0.0,
#                  0.4, 0.2, 0, 0.3,
#                  0.4, -0.2, 0, 0.3]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]

num_actions: 12
num_obs: 65

cmd_init: [0.7, 0, 0.0]
# cmd_init: [0.0, 0.0, 1.0]