# 
# policy_path: "{LEGGED_GYM_ROOT_DIR}/deploy/pre_train/h1_2/motion.pt"
# policy_path: "/home/bcj/unitree_rl_gym/logs/h1_2/Dec22_21-19-43_arm_down/exported/policy_lstm_1.pt"  # arm down
# policy_path: "/home/bcj/unitree_rl_gym/logs/h1_2/Dec30_10-29-21_period_0.8_offset_0.5/exported/policy_lstm_1.pt" # 12.27 video

policy_path: "/home/bcj/unitree_rl_gym/logs/h1_2/Dec30_13-53-43_debug/exported/policy_lstm_1.pt"

# xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/h1_2/scene.xml"
xml_path: "{LEGGED_GYM_ROOT_DIR}/resources/robots/h1_2/scene_arm_down.xml"


# Total simulation time
simulation_duration: 60.0
# Simulation time step
simulation_dt: 0.002
# Controller update frequency (meets the requirement of simulation_dt * controll_decimation=0.02; 50Hz)
control_decimation: 10

kps: [200, 200, 200, 300, 30, 30, 200, 200, 200, 300, 30, 30]
kds: [2.5, 2.5, 2.5, 4, 6, 6,  2.5, 2.5, 2.5, 4, 6, 6]

# default_angles: [0, -0.16, 0.0, 0.36, -0.2, 0.0, 
#                  0, -0.16, 0.0, 0.36, -0.2, 0.0]

default_angles: [0, -0.4, 0.0, 0.8, -0.4, 0.0, 
                 0, -0.4, 0.0, 0.8, -0.4, 0.0,]

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
action_scale: 0.25
cmd_scale: [2.0, 2.0, 0.25]
num_actions: 12
num_obs: 47

cmd_init: [0.0, 0, 0]